attendance/urls.py
from django.urls import path
from .views import *

app_name = 'attendance'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterView.as_view(), name='register'),
    path('send-mail/', SendMailView.as_view(), name='send-mail'),
    path('verify-otp/', VerifyOTPView.as_view(), name='verify-otp'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('teacher/', TeacherView.as_view(), name='teacher'),
    path('teacher/submit-email/', TeacherSubmitEmailView.as_view(), name='teacher-submit-email'),
    path('teacher/add-class/', AddClassView.as_view(), name='add-class'),
    path('student/', StudentView.as_view(), name='student'),
    path('student/submit-roll/', SubmitRollView.as_view(), name='submit-roll'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

thapar_connect/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('attendance.urls')),
]

attendance/models.py
from django.db import models

class UserInfo(models.Model):
    name = models.CharField(max_length=100)
    profile_pic = models.FileField(upload_to='profile_pics/', blank=True)
    email_id = models.EmailField(max_length=255, unique=True)
    password = models.CharField(max_length=60)

class Teacher(models.Model):
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    thapar_email = models.EmailField()

class Student(models.Model):
    user = models.OneToOneField(UserInfo, on_delete=models.CASCADE)
    roll_no = models.IntegerField(unique=True)

class ClassRoom(models.Model):
    year = models.IntegerField()
    class_code = models.CharField(max_length=20)
    class_key = models.CharField(max_length=6)

class ClassStudents(models.Model):
    class_room = models.ForeignKey(ClassRoom, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, null=True, on_delete=models.SET_NULL)
    serial_no = models.IntegerField()

class Subjects(models.Model):
    subject_name = models.CharField(max_length=60)
    subject_code = models.CharField(max_length=10)

class Lecture(models.Model):
    teacher = models.ForeignKey(Teacher, null=True, on_delete=models.SET_NULL)
    class_room = models.ForeignKey(ClassRoom, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subjects, on_delete=models.CASCADE)
    class_type = models.CharField(max_length=1)

class AttendanceInfo(models.Model):
    lecture = models.ForeignKey(Lecture, on_delete=models.CASCADE)
    data_time = models.DateTimeField()
    type = models.CharField(max_length=20)

class AttendanceLog(models.Model):
    attendance_info = models.ForeignKey(AttendanceInfo, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    is_present = models.BooleanField()


class Encodings(models.Model):
    user = models.ForeignKey(UserInfo, on_delete=models.CASCADE)
    encoding = models.TextField()


#---------------------------------------------------------------#
class Blog(models.Model):
    name = models.CharField(max_length=100)
    tagline = models.TextField()

    def __str__(self):
        return self.name

class Author(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()

    def __str__(self):
        return self.name

class Entry(models.Model):
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    headline = models.CharField(max_length=255)
    body_text = models.TextField()
    pub_date = models.DateField()
    mod_date = models.DateField()
    authors = models.ManyToManyField(Author)
    n_comments = models.IntegerField()
    n_pingbacks = models.IntegerField()
    rating = models.IntegerField()

    def __str__(self):
        return self.headline

attendance/forms.py
from django import forms

class LoginForm(forms.Form):
    #CHOICES = ((1, 'Teacher'), (2, 'Student'),)
    #account_type = forms.ChoiceField(choices=CHOICES)
    email_id = forms.CharField(max_length=255)
    password = forms.CharField(widget=forms.PasswordInput(), max_length=60)

class RegisterForm(forms.Form):
    name = forms.CharField(max_length=100)
    email_id = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput(), max_length=60)

class OTPForm(forms.Form):
    otp = forms.IntegerField(min_value=100000, max_value=999999)

class RollForm(forms.Form):
    roll_no = forms.IntegerField(max_value=9999999999)

class AttendanceVideoForm(forms.Form):
    video = forms.FileField

class EmailForm(forms.Form):
    email_id = forms.EmailField()

class AddClassForm(forms.Form):
    class_name = forms.CharField(max_length=20)

attendance/views.py
from django.views import View
from django.shortcuts import render
from django.http import HttpResponse
from .forms import *
from .models import *
from django.core.mail import EmailMessage
from django.shortcuts import redirect
import random

class SendMailView(View):
    email = EmailMessage('Test Email', 'Hello papa ji kaise he?', to=['vipuls526@gmail.com'])
    def get(self, request):
        if(self.email.send()):
            return HttpResponse('<h1>Message Sent!</h1>')
        else:
            return HttpResponse('<h1>Message Not Sent!</h1>')

class IndexView(View):
    def get(self, request):
        if request.session.has_key('user'):
            return render(request, 'attendance/index.html')

        return redirect('attendance:login')

class RegisterView(View):
    register_template = 'attendance/register.html'
    register_form = RegisterForm
    def get(self, request):
        return render(request, self.register_template, {'register_form': self.register_form})

    def post(self, request, *args, **kwargs):
        form = self.register_form(request.POST)
        if form.is_valid():
            request.session['process'] = 1
            otp = random.randint(100000, 999999)
            request.session['otp'] = otp
            name = form.cleaned_data['name']
            request.session['name'] = name
            email_id = form.cleaned_data['email_id']
            request.session['email_id'] = email_id
            request.session['password'] = form.cleaned_data['password']
            email = EmailMessage('Verify OTP',
                                 'Hey ' + str(name) + ' - ' + str(otp) + ' is your otp to register to Thapar Connect.',
                                 to=[email_id])
            email.send()
            return redirect('attendance:verify-otp')

        return render(request, self.register_template, {'register_form': self.register_form})

class LoginView(View):
    login_template = 'attendance/login.html'
    login_form = LoginForm
    def get(self, request):
        return render(request, self.login_template, {'login_form': self.login_form})

    def post(self, request):
        form = self.login_form(request.POST)
        if form.is_valid():
            query = UserInfo.objects.filter(email_id=form.cleaned_data['email_id'])
            query = query.filter(password=form.cleaned_data['password'])
            total = query.count()
            if total == 1:
                for result in query:
                    id = result.id
                    request.session['user'] = id
                    return redirect('attendance:index')

        return render(request, self.login_template, {'login_form': self.login_form})

class VerifyOTPView(View):
    otp_template = 'attendance/verify-otp.html'
    otp_form = OTPForm
    def get(self, request):
        return render(request, self.otp_template, {'otp_form': self.otp_form})

    def post(self, request):
        form = self.otp_form(request.POST)
        if form.is_valid():
            otp = int(form.cleaned_data['otp'])
            if otp == request.session['otp']:
                process = int(request.session['process'])
                # Process-1 is for user registration
                if process == 1:
                    user = UserInfo()
                    user.name = request.session['name']
                    user.email_id = request.session['email_id']
                    user.password = request.session['password']
                    user.save()
                    return redirect('attendance:login')
                    account_type = int(request.session['account_type'])

        return render(request, self.otp_template, {'otp_form': self.otp_form})

class SubmitRollView(View):
    roll_template = 'attendance/submit-roll.html'
    roll_form = RollForm
    def get(self, request):
        if request.session.has_key('user'):
            return render(request, self.roll_template, {'roll_form': self.roll_form})
        return redirect('attendance:index')

    def post(self, request):
        if request.session.has_key('user'):
            form = self.roll_form(request.POST)
            if form.is_valid():
                user = getUser(int(request.session['user']))
                student = Student()
                student.user = user
                student.roll_no = form.cleaned_data['roll_no']
                student.save()
                return redirect('attendance:student')

        return render(request, self.roll_template, {'roll_form': self.roll_form})

class ProfileView(View):
    def get(self, request):
        if request.session.has_key('user'):
            id = request.session['user']
            query = UserInfo.objects.filter(id = int(id))
            for result in query:
                user = result
                break

            context = {
                'user': user,
            }
            return render(request, 'attendance/profile.html', context)

        return redirect('attendance:login')

class TeacherView(View):
    def get(self, request):
        if request.session.has_key('user'):
            user = getUser(int(request.session['user']))
            query = Teacher.objects.filter(user = user)
            if query.count() == 1:
                return render(request, 'attendance/teacher.html')
            elif query.count() == 0:
                return redirect('attendance:teacher-submit-email')
        return redirect('attendance:index')

class TeacherSubmitEmailView(View):
    email_template = 'attendance/teacher-submit-email.html'
    email_form = EmailForm
    def get(self, request):
        if request.session.has_key('user'):
            return render(request, self.email_template, {'email_form': self.email_form})
        return redirect('attendance:index')

    def post(self, request):
        if request.session.has_key('user'):
            form = self.email_form(request.POST)
            if form.is_valid():
                email = form.cleaned_data['email_id']
                domain = email.split('@')[1]
                if domain == 'thapar.edu':
                    user = getUser(int(request.session['user']))
                    teacher = Teacher()
                    teacher.user = user
                    teacher.thapar_email = email
                    teacher.save()
                    return redirect('attendance:teacher')
            return render(request, self.email_template, {'email_form': self.email_form})
        return redirect('attendance:index')

class AddClassView(View):
    def get(self, request):
        return render(request, 'attendance/add-class.html')

class StudentView(View):
    def get(self, request):
        if request.session.has_key('user'):
            user = getUser(int(request.session['user']))
            query = Student.objects.filter(user = user)
            if query.count() == 1:
                return render(request, 'attendance/student.html')
            elif query.count() == 0:
                return redirect('attendance:submit-roll')

        return redirect('attendance:index')

class LogoutView(View):
    def get(self, request):
        try:
            del request.session['user']
        except KeyError:
            pass
        return redirect('attendance:login')

def getUser(id):
    query = UserInfo.objects.filter(id = id)
    count = query.count()
    for result in query:
        user = result
        return user

attendance/templates/attendance/add-class.html
{% extends 'attendance/base.html' %}

attendance/templates/attendance/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'attendance/css/main.css' %}"/>
    <title>{% block site_title %}Thapar Connect - Untitled{% endblock %}</title>
</head>
<body>
<section class="main-site">
    <header class="site-head">
        <div class="site-name"><h2>Thapar Connect</h2></div>
        <div class="site-button"><a href="{% block site_button_link %}{% url 'attendance:logout' %}{% endblock %}">
            <button class="site-button">{% block site_button_name %}Logout{% endblock %}</button></a></div>
        <div style="clear:both;"></div>
    </header><hr/>
    <nav class="site-nav">
        {% block site_nav %}
            <ul class="site-nav-list">
                <a href="{% url 'attendance:index' %}"><li>Home</li></a>
                <a href="{% url 'attendance:profile' %}"><li>Profile</li></a>
                <!--<a href="#"><li>News</li></a>
                <a href="#"><li>Messages</li></a>
                <a href="#"><li>Notifications</li></a>-->
                <div style="clear: both"/>
            </ul><hr/>
        {% endblock %}
    </nav>
    <section class="site-body">
        {% block site_body %}{% endblock %}
    </section>
    <footer>
        <div class="site-footer">
            &copy; Copyright 2018 | This website is developed and managed by Vipul Sharma.
        </div>
    </footer>
</section>
</body>
</html>

attendance/templates/attendance/form.html
{% extends 'attendance/base.html' %}
{% block site_nav %}{% endblock %}
{%  block site_body %}
    <div class="form-div">
        <header class="form-head">
            <h3>{% block form_head %}{% endblock %}</h3><hr/>
        </header>
        <section class="form-body">
            {% block form_body %}

            {% endblock %}
        </section>
        <footer class="form-foot">
            <h3>{% block form_foot %}{% endblock %}</h3>
        </footer>
    </div>
{% endblock %}

attendance/templates/attendance/index.html
{% extends 'attendance/base.html' %}
{% block site_title %}Thapar Connect - Home{% endblock %}
{% block site_body %}
    <div class="main-div">
        <header class="main-div-head">
            <h3>Apps</h3>
        </header>
        <section class="main-div-section">
            <div class="app-div">
                <header class="app-name">Teacher App</header>
                <section class="app-body">Mark Attendance and much more.</section>
                <footer class="app-foot"><a href="{% url 'attendance:teacher' %}"><button>Click Here</button></a></footer>
            </div><hr/>
            <div class="app-div">
                <header class="app-name">Student App</header>
                <section class="app-body">Get more connected to your college.</section>
                <footer class="app-foot"><a href="{% url 'attendance:student' %}"><button>Click Here</button></a></footer>
            </div><hr/>
        </section>
        <!--<footer class="main-div-foot">
            <button>Load More</button>
        </footer>-->
    </div>
{% endblock %}

attendance/templates/attendance/login.html
{% extends 'attendance/form.html' %}
{% block site_title %}Thapar Connect - Login{% endblock %}
{% block site_button_link %}{% url 'attendance:register' %}{% endblock %}
{% block site_button_name %}Register{% endblock %}

{% block form_head %}Login Form{% endblock %}
{% block form_body %}
    <form class="site-form" method="post" action="{% url 'attendance:login' %}">
        {% csrf_token %}
        {{ login_form.as_p }}
        <button type="form-submit">Login</button>
    </form>
{% endblock %}

attendance/templates/attendance/profile.html
{% extends 'attendance/base.html' %}
{% block site_title %}Thapar Connect - Profile{% endblock %}
{% block site_body %}
    <div class="profile-image">
        <img src="#" width="200px" height="200px"/>
        <button>Change Profile Picture</button>
        <h3>{{ user.name }}</h3>
    </div><hr/>
{% endblock %}

attendance/templates/attendance/register.html
{% extends 'attendance/form.html' %}
{% block site_title %}Thapar Connect - Register{% endblock %}
{% block site_button_link %}{% url 'attendance:login' %}{% endblock %}
{% block site_button_name %}Login{% endblock %}

{% block form_head %}Register Form{% endblock %}
{% block form_body %}
    <form class="site-form" method="post" action="{% url 'attendance:register' %}">
        {% csrf_token %}
        {{ register_form.as_p }}
        <button type="form-submit">Register</button>
    </form>
{% endblock %}

attendance/templates/attendance/student.html
{% extends 'attendance/base.html' %}
{% block site_title %}Thapar Connect - Student{% endblock %}

attendance/templates/attendance/submit-roll.html
{% extends 'attendance/base.html' %}
{% block site_title %}Thapar Connect - Submit Roll{% endblock %}
{% block site_button_link %}{% url 'attendance:login' %}{% endblock %}
{% block site_button_name %}Login{% endblock %}

{% block site_body %}
    <form class="site-form" method="post" action="{% url 'attendance:submit-roll' %}">
        {% csrf_token %}
        {{ roll_form.as_p }}
        <button type="form-submit">Submit</button>
    </form>
{% endblock %}

attendance/templates/attendance/teacher-submit-email.html
{% extends 'attendance/base.html' %}
{% block site_title %}Thapar Connect - Teacher | Submit Email{% endblock %}
{% block site_button_link %}{% url 'attendance:login' %}{% endblock %}
{% block site_button_name %}Login{% endblock %}

{% block site_body %}
    <form class="site-form" method="post" action="{% url 'attendance:teacher-submit-email' %}">
        {% csrf_token %}
        {{ email_form.as_p }}
        <button type="form-submit">Submit</button>
    </form>
{% endblock %}

attendance/templates/attendance/teacher.html
{% extends 'attendance/base.html' %}
{% block site_title %}Thapar Connect - Teacher{% endblock %}
{% block site_body %}
    <div class="main-div">
        <header class="main-div-head"><h3>All your classes</h3></header>
        <section class="main-div-body">
            <div class="app-div">
                <header class="app-name"><pre>Class Name</pre></header>
                <section class="app-body">
                    Class Details
                </section>
                <footer class="app-body"><button>Click Here</button></footer>
            </div>
        </section><hr/>
    </div>
    <div class="main-div">
        <header class="main-div-head"><h3>Explore More</h3></header>
        <section class="main-div-body">
            <div class="app-div">
                <header class="app-name"><pre>Add Class</pre></header>
                <section class="app-body">
                    Add all your classes to get directly connected.
                </section>
                <footer class="app-body"><a href="{% url 'attendance:add-class' %}"><button>Click Here</button></a></footer>
            </div>
        </section><hr/>
    </div>
{% endblock %}

attendance/templates/attendance/verify-otp.html
{% extends 'attendance/form.html' %}
{% block site_title %}Thapar Connect - Verify OTP{% endblock %}
{% block site_button_link %}{% url 'attendance:login' %}{% endblock %}
{% block site_button_name %}Login{% endblock %}

{% block form_head %}Verify OTP{% endblock %}
{% block form_body %}
    <form class="site-form" method="post" action="{% url 'attendance:verify-otp' %}">
        {% csrf_token %}
        {{ otp_form.as_p }}
        <button type="form-submit">Verify</button>
    </form>
{% endblock %}